export const ActionTypes = {
  CREATE_REQUEST: "CREATE_REQUEST",
  SUBMIT_REQUEST: "SUBMIT_REQUEST",
  APPROVE_REQUEST: "APPROVE_REQUEST",
  REJECT_REQUEST: "REJECT_REQUEST",
  ADD_COMMENT: "ADD_COMMENT",
  EDIT_COMMENT: "EDIT_COMMENT",
  ARCHIVE_COMMENT: "ARCHIVE_COMMENT",
  LOGIN_USER: "LOGIN_USER",
  NAVIGATE: "NAVIGATE"
};